accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/comment/', views.comment_list, name='comment_list'),
]

cloneit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.movie_detail, name='movie_detail'),
    path('participant/<int:id>/', views.participant_detail, name='participant_detail'),
    path('<int:id>/comments/create/', views.comments_create, name='comments_create'),

    path('comments/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Movie(models.Model):
    # 영화 정보
    AGE_LIMIT_CHOICES = (
        ('all', '전체관람가'),
        ('12', '12세 이상 관람가'),
        ('15', '15세 이상 관람가'),
        ('rated-R', '청소년 관람불가'),
        ('restricted', '제한상영가'),
    )
    title = models.CharField(max_length=100)    
    duration = models.PositiveIntegerField(default=0)
    age_limit = models.CharField(max_length=10, choices=AGE_LIMIT_CHOICES)
    audience_count = models.PositiveIntegerField(default=0)
    production_company = models.CharField(max_length=100)
    release_year = models.PositiveIntegerField()

    # 2차 수정목록 장르,국가,평점
    participants = models.ManyToManyField('Participant', through='Role')
    # 장르 M:N 으로 수정필요
    # 원래는 char필드였음 genre = models.CharField(max_length=100)
    genres = models.ManyToManyField('Genre', related_name='movies')

    # 제작국가도 M:N으로 수정필요, 나라별 합작/공동제작의 경우를 위해
    countries = models.ManyToManyField('Country')


    # rating은 댓글남기면서 평점을 매기면, 모든 댓글의 평균점수를 나타내는 방향으로 수정필요
    rating = models.FloatField()

    def __str__(self):
        return self.title

class Participant(models.Model):
    # 사람 신상정보
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Role(models.Model):
    ROLE_CHOICES = (
        ('director', '감독'),
        ('leading', '주연'),
        ('supporting', '조연'),
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)
    role_type = models.CharField(max_length=20, choices=ROLE_CHOICES)

    def __str__(self):
        return f"{self.movie.title} - {self.participant.name} - {self.get_role_type_display()}"
    
    
class Genre(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Country(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(default=5)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'movie', 'rating'],
                name='one_by_one',
            ),
        ]

    def __str__(self):
        return f"{self.user.username} - {self.movie.title} - {self.content}"

movies/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(attrs={'rows':'1'}), 
        label='',
    )
    rating = forms.ChoiceField(
        choices=[(str(i), str(i)) for i in range(1, 6)],
        label='rate',
        required=True,
    )
    class Meta:
        model = Comment
        fields = ('content', 'rating',)

movies/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Movie, Participant, Role, Comment
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
import requests
from bs4 import BeautifulSoup

# Create your views here.

def index(request):
    movies = Movie.objects.all()

    for movie in movies:
        poster_url = get_image(movie.title)
        movie.image = poster_url
        
        comments = Comment.objects.filter(movie=movie)

        movie.average_rating = average_stars(comments)


    context = {
        'movies': movies,
        'poster_url': poster_url,
    }

    return render(request, 'movies/index.html', context)

def movie_detail(request, id):
    movie = get_object_or_404(Movie, id=id)
    # Movie모델에서 object 찾는데, 없으면 404페이지
    # 들어온 id와 일치하는 것 찾아서 movie에 저장

    movie_roles = Role.objects.filter(movie=movie)
    # 제목 - 참가자이름 - 역할 로 Role에 저장된것을 가져옴

    genres = movie.genres.all()
    countries = movie.countries.all()
    comments = Comment.objects.filter(movie=movie)

    average_rating = average_stars(comments)

    poster_url = get_image(movie.title)

    # 이미 평가한 유저는 폼 안보여줌
    already_done = Comment.objects.filter(user=request.user, movie=movie).exists()

    if already_done:
        comment_form = None
    else:
        comment_form = CommentForm()

    context = {
        'movie': movie,
        'movie_roles': movie_roles,
        'genres': genres,
        'countries': countries,
        'comments': comments,
        'comment_form': comment_form,
        'poster_url': poster_url,
        'average_rating': average_rating,
        'already_done': already_done,
    }
    return render(request, 'movies/movie_detail.html', context)

def participant_detail(request, id):
    participant = get_object_or_404(Participant, id=id)

    roles = participant.role_set.all()
    # models.py 에서 movie클래스안에 participants related_name='roles'로 설정함

    context = {
        'participant': participant,
        'roles': roles,
    }

    return render(request, 'movies/participant_detail.html', context)

def comments_create(request, id):
    movie = get_object_or_404(Movie, id=id)


    if request.method == 'POST':
        form = CommentForm(request.POST)
        user = request.user
        

        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.movie = movie
            comment.save()
            print('댓글저장됨')
            
            return redirect('movies:movie_detail', id=id)
    else:
        form = CommentForm()
    
    context = {
        'form': form,
        'movie': movie,
    }
    return render(request, 'movies/movie_detail.html', context)



@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if request.method == 'POST':
        comment.delete()
        return redirect('movies:movie_detail', id=comment.movie.id)
    


def get_image(query):
    URL = f"https://www.bing.com/images/search?q=위키+{query}+영화포스터&first=1"

    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"
    }

    response = requests.get(URL, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    urls_result = soup.find_all("img",class_="mimg", limit=5)


    image_urls = []
    for image in urls_result:
        if "src" in image.attrs:
            image_urls.append(image["src"])

    if urls_result:
        first_image_url = urls_result[0]["src"]
        # print('검색결과 첫번째이미지:',first_image_url)
        return first_image_url


def average_stars(comments):
    rating_sum = 0
    count = 0

    for comment in comments:
        rating_sum += comment.rating
        count += 1
    # 전체 코멘트 불러들여서, 처음부터 끝까지 별점 다 더해서 rating_sum에 저장
    # 카운트는 전체 코멘트 숫자

    if count == 0:
        average_star = 0
        # 코멘트가 아무것도 없으면 평점도 0
    else:
        average_star = round(rating_sum / count, 2)
        # 전체점수 / 코멘트수 => 소수점2자리까지반올림
    return average_star

movies/templates/movies/_card.html
{% load bootstrap5 %}
<div class="col-md-auto">
    <div class="card mb-5" style="width: 12rem;">
        <a href="{% url 'movies:movie_detail' movie.id %}">
            <img src="{{ movie.image }}" class="card-img-top" alt="...">
        </a>
        <div class="card-body">
            <p>{{ movie.title }} | ★{{ movie.average_rating }} ({{ movie.comment_set.count }}명 평가)</p>
        </div>
    </div>
</div>

movies/templates/movies/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %} 

{% block content %}

        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://postfiles.pstatic.net/MjAyMzA2MjRfMjE0/MDAxNjg3NTcxMzc1MTMx.4Ck-W0FvYw3eDFAsyaApwe7g9U9knbQJp78cDI9Yfqsg.Hl5vYSTumz2PgWuh-OqLIvklFsA-eghtcWiwcw0XvN0g.JPEG.ban1329/34.jpg?type=w966" alt="..." /></div>
                <div class="col-lg-5">
                    <h1 class="font-weight-light">최신작</h1>
                    <h3>미션 임파서블: 데드 레코닝 PART ONE</h3>
                    <h5>가장 위험한 작전, 그의 마지막 선택</h5>
                    <p>모든 인류를 위협할 새로운 무기를 추적하게 된 에단 헌트(톰 크루즈)와 IMF팀은 이 무기가 인류의 미래를 통제할 수 있다는 사실을 알게 된다. 전 세계가 위태로운 상황에 처한 가운데, 이를 추적하던 에단 헌트에게 어둠의 세력까지 접근하고 마침내 미스터리하고 강력한 빌런과 마주하게 된 그는 가장 위험한 작전을 앞두고 자신이 아끼는 사람들의 생명과 중요한 임무 사이에서 선택을 해야 하는 상황에 놓이게 되는데…</p>
                    <a class="btn btn-primary" href="{% url 'movies:movie_detail' 37 %}">자세히</a>
                </div>
            </div>
            <!-- Call to Action-->
            <div class="card text-white bg-secondary my-5 py-4 text-center">
                <div class="card-body"><h2 class="text-white m-0">영화 평가수 TOP 5 </h2></div>
            </div>
            <!-- Content Row-->
            <div class="row gx-4 gx-lg-5">

                    {% for movie in movies %}
                        {% include 'movies/_card.html' %}
                    {% endfor %}

            </div>
        </div>
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; 영화영화영 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="/static/index_sample/js/scripts.js"></script>
{% endblock %}

movies/templates/movies/index_ori.html
{% extends 'base.html' %}

{% block content %}
<h1>영화정보</h1>


<div class="row">
    {% for movie in movies %}
        {% include 'movies/_card.html' %}
    {% endfor %}
</div>

<!-- {% for movie in movies %}
<p>
    {% if movie.image %}
    <img src="{{ movie.image }}" alt="." width="100">
    {% endif %}
    <a href="{% url 'movies:movie_detail' movie.id %}">{{ movie.title }}</a>
</p>
{% endfor %} -->

{% endblock %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'index_sample/css/style.css' %}">
{% endblock %}

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% load static %}
{% load humanize %}

{% block content %}

<!-- Header - set the background image for the header in the line below-->
<header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
    <div class="text-center my-5">
        <img class="img-fluid rounded mb-4" src="{{ poster_url }}" alt="..." />
        <h1 class="text-white fs-3 fw-bolder">{{ movie.title }}</h1>
        <p class="text-white-50 mb-0">{{ movie.release_year }}</p>
    </div>
</header>
<!-- Content section-->
<section class="py-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6">
            <ul>
                <li>개봉년도: {{ movie.release_year }}</li>
                <li>연령제한: {{ movie.get_age_limit_display }}</li>
                <li>장르:
                    {% for genre in movie.genres.all %}
                    {{ genre.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </li>
                <li>국가:
                    {% for country in movie.countries.all %}
                    {{ country.name }}{% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </li>
                <li>상영시간: {{ movie.duration }}분</li>
                <!-- <li>평점: {{ movie.rating }}</li> -->
                <li>관람객수: {{ movie.audience_count | intcomma }}명</li>
                <li>제작사: {{ movie.production_company }}</li>
            </ul>
            <h2>출연/제작</h2>
            <ul>
                {% for role in movie_roles %}
                {% if role.role_type == 'director' %}
                <li>감독: <a href="{% url 'movies:participant_detail' role.participant.id %}">{{role.participant.name}}</a></li>
                {% endif %}
                {% endfor %}

                {% for role in movie_roles %}
                {% if role.role_type == 'leading' %}
                <li>주연: <a href="{% url 'movies:participant_detail' role.participant.id %}">{{role.participant.name}}</a></li>
                {% endif %}
                {% endfor %}

                {% for role in movie_roles %}
                {% if role.role_type == 'supporting' %}
                <li>조연: <a href="{% url 'movies:participant_detail' role.participant.id %}">{{role.participant.name}}</a></li>
                {% endif %}
                {% endfor %}

                {% for role in movie_roles %}
                {% if role.role_type != 'director' and role.role_type != 'leading' and role.role_type != 'supporting' %}
                <li><a href="{% url 'movies:participant_detail' role.participant.id %}">{{ role.participant.name }}</a>
                </li>
                {% endif %}
                {% endfor %}

            </ul>
        </div>
        </div>
    </div>
</section>
<!-- Image element - set the background image for the header in the line below-->
<div class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/4ulffa6qoKA/1200x800')">
    <!-- Put anything you want here! The spacer below with inline CSS is just for demo purposes!-->
    <div style="height: 1rem"></div>
</div>
<!-- Content section-->
<section class="py-5">
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h3 style="display: inline;">코멘트 / 평균 ★{{ average_rating }} </h3>
                <h6 style="display: inline;">({{ comments.count }}개) </h6>

                {% if request.user.is_authenticated %}
                {% if not already_done %}
                <form method="POST" action="{% url 'movies:comments_create' movie.id %}">
                    {% csrf_token %}

                    <style>
                        .form-select {
                            width: 80px;
                        }
                    </style>

                    <div class="d-flex align-items-center">
                        {{ comment_form.content }}
                        <select class="form-select form-select-sm" name="rating" required>
                            <option value="" selected disabled>점수</option>
                            <option value="5">5</option>
                            <option value="4">4</option>
                            <option value="3">3</option>
                            <option value="2">2</option>
                            <option value="1">1</option>
                        </select>
                        <button type="submit" class="btn btn-primary btn-sm">작성</button>
                    </div>
                </form>
                {% else %}
                <p>이미 평가한 영화입니다.</p>
                {% endif %}
                {% else %}
                <p>작성하시려면 로그인이 필요합니다.</p>
                {% endif %}

                {% for comment in comments %}
                <div style="display: flex; align-items: center;">
                    <p class="commnet-text"> ★{{ comment.rating }}점 <a
                            href="{% url 'accounts:profile' comment.user.username %}">
                            {{ comment.user.username }}</a>
                        - {{ comment.content }} | {{ comment.created_at | naturaltime }} </p>
                    {% if user.is_authenticated and user == comment.user %}
                    <form method="POST" action="{% url 'movies:comment_delete' comment.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-danger btn-sm"
                            style="align-self: baseline;">삭제</button>
                    </form>
                    {% endif %}
                </div>
                {% empty %}
                <p>작성된 댓글이 없습니다.</p>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; 영화영화영 2023</p>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="/static/movie_detail_sample/js/scripts.js"></script>
{% endblock %}

movies/templates/movies/movie_detail_ori.html
{% extends 'base.html' %}

{% load humanize %}
{% load static %} 
{% block content %}
<h1>{{ movie.title }}</h1>
<img src="{{ poster_url }}" alt="영화 포스터">
<ul>
    <li>개봉년도: {{ movie.release_year }}</li>
    <li>연령제한: {{ movie.get_age_limit_display }}</li>
    <li>장르:
        {% for genre in movie.genres.all %}
        {{ genre.name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </li>
    <li>국가:
        {% for country in movie.countries.all %}
        {{ country.name }}{% if not forloop.last %}, {% endif %}
        {% endfor %}
    </li>
    <li>상영시간: {{ movie.duration }}분</li>
    <!-- <li>평점: {{ movie.rating }}</li> -->
    <li>관람객수: {{ movie.audience_count | intcomma }}명</li>
    <li>제작사: {{ movie.production_company }}</li>
</ul>
<h2>출연/제작</h2>
<ul>
    {% for role in movie_roles %}
    {% if role.role_type == 'director' %}
    <li>감독: <a href="{% url 'movies:participant_detail' role.participant.id %}">{{ role.participant.name }}</a></li>
    {% endif %}
    {% endfor %}

    {% for role in movie_roles %}
    {% if role.role_type == 'leading' %}
    <li>주연: <a href="{% url 'movies:participant_detail' role.participant.id %}">{{ role.participant.name }}</a></li>
    {% endif %}
    {% endfor %}

    {% for role in movie_roles %}
    {% if role.role_type == 'supporting' %}
    <li>조연: <a href="{% url 'movies:participant_detail' role.participant.id %}">{{ role.participant.name }}</a></li>
    {% endif %}
    {% endfor %}

    {% for role in movie_roles %}
    {% if role.role_type != 'director' and role.role_type != 'leading' and role.role_type != 'supporting' %}
    <li><a href="{% url 'movies:participant_detail' role.participant.id %}">{{ role.participant.name }}</a></li>
    {% endif %}
    {% endfor %}

</ul>
<h3 style="display: inline;">코멘트 / 평균 ★{{ average_rating }} </h3>
<h6 style="display: inline;">({{ comments.count }}개) </h6>

{% if request.user.is_authenticated %}
    {% if not already_done %}
    <form method="POST" action="{% url 'movies:comments_create' movie.id %}">
        {% csrf_token %}

        <style>
            .form-select {
                width: 80px;
            }
        </style>

        <div class="d-flex align-items-center">
            {{ comment_form.content }}
            <select class="form-select form-select-sm" name="rating" required>
                <option value="" selected disabled>점수</option>
                <option value="5">5</option>
                <option value="4">4</option>
                <option value="3">3</option>
                <option value="2">2</option>
                <option value="1">1</option>
            </select>
            <button type="submit" class="btn btn-primary btn-sm">작성</button>
        </div>
    </form>
    {% else %}
    <p>이미 평가한 영화입니다.</p>
    {% endif %}
{% else %}
<p>작성하시려면 로그인이 필요합니다.</p>
{% endif %}

{% for comment in comments %}
<div style="display: flex; align-items: center;">
    <p class="commnet-text"> ★{{ comment.rating }}점 <a href="{% url 'accounts:profile' comment.user.username %}"> 
        {{ comment.user.username }}</a>
        - {{ comment.content }} | {{ comment.created_at | naturaltime }} </p>
    {% if user.is_authenticated and user == comment.user %}
    <form method="POST" action="{% url 'movies:comment_delete' comment.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-danger btn-sm" style="align-self: baseline;">삭제</button>
    </form>
    {% endif %}
</div>
{% empty %}
<p>작성된 댓글이 없습니다.</p>
{% endfor %}

{% endblock %}

{% block extracss %}
    <link rel="stylesheet" href="{% static 'movie_detail_sample/css/style.css' %}">
{% endblock %}

movies/templates/movies/participant_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ participant.name }}</h1>
    
    <h2>참여한 영화</h2>
    <ul>
        {% for role in roles %}
        <li><a href="{% url 'movies:movie_detail' role.movie.id %}">{{ role.movie.title }}</a> {% if role.role_type %} ({{ role.get_role_type_display }}) {% endif %}</li>
        {% endfor %}
    </ul>
{% endblock %}