accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/comment/', views.comment_list, name='comment_list'),
]

cloneit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.movie_detail, name='movie_detail'),
    path('participant/<int:id>/', views.participant_detail, name='participant_detail'),
    path('<int:id>/comments/create/', views.comments_create, name='comments_create'),

    path('comments/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from movies.models import Movie

# Create your models here.
class User(AbstractUser):
    pass
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from .models import User
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta): # UCF 상속, model만 내것으로수정하고 나머지 그대로
        model = get_user_model()
        fields = ('username', )
        

class CustomAuthenticationForm(AuthenticationForm):
    pass

class CustomUserChangeForm(UserChangeForm):
    password = None
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreationForm, CustomAuthenticationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if  form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form' : form
    }

    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('movies:index')
        
    else:
        form = CustomAuthenticationForm()

    context = {
        'form' : form,
    }

    return render(request, 'accounts/form.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')


@login_required
def comment_list(request):
    comments = request.user.like_set.all().order_by('-created_at')

    context = {
        'comments': comments,
    }

    return render(request, 'accounts/comment_list.html', context)


def profile(request, username):
    User = get_user_model()
    user_info = get_object_or_404(User, username=username)

    comments = user_info.comments.all().order_by('-created_at')

    context = {
        'user_info': user_info,
        'comments': comments,
    }

    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/form.html
{% extends 'base.html' %}
<!--회원가입,로그인 폼-->
{% load bootstrap5 %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary" value="제출">
    </form>

{% endblock %} 

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}

<div>
    <h1 class="text-center">{{user_info.username}}님</h1>
</div>

<div class="m-2">
    <div class="row">
        <div class="col-9">
            <p class="d-flex"> 영화평가: {{ user_info.comments.count }}개</p>
            <br>
        </div>
        <div class="col-12">
            {% for comment in comments %}
            <div class="d-flex">
                <p><a href="{% url 'movies:movie_detail' comment.movie.id %}">{{ comment.movie.title }}</a> 한줄평 : ★ {{ comment.rating }} | {{ comment.content }} | {{ comment.created_at |naturaltime}}</p>
                {% if user.is_authenticated and user == comment.user %}
                <form method="POST" action="{% url 'movies:comment_delete' comment.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger btn-sm"
                        style="align-self: baseline;">삭제</button>
                </form>
                {% endif %}
            </div>
            {% empty %}
            <p>작성된 댓글이 없습니다.</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}