accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/comment/', views.comment_list, name='comment_list'),
]

cloneit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.movie_detail, name='movie_detail'),
    path('participant/<int:id>/', views.participant_detail, name='participant_detail'),
    path('<int:id>/comments/create/', views.comments_create, name='comments_create'),

    path('comments/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

templates/_nav.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'movies:index' %}">
        <i class="fa-solid fa-house"></i>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'accounts:profile' user.username %}">
                  {{user}}

                </a>
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout
                  <i class="fa-solid fa-right-from-bracket"></i>
                </a>

            {% else %}
                <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>

            {% endif %}
        </div>
      </div>
    </div>
</nav>

templates/base.html
{% load bootstrap5 %}
{% load static %} 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>영화영화영 - 영화정보사이트</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="css/styles.css" rel="stylesheet" />


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    {% include '_nav.html' %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% bootstrap_javascript %}
    <script src="https://kit.fontawesome.com/bc66d14ed4.js" crossorigin="anonymous"></script>
</body>
</html>